python:
  - changed-files:
      - any-glob-to-any-file: "**/*.py"

yaml:
  - changed-files:
      - any-glob-to-any-file:
          - "**/*.yml"
          - "**/*.yaml"

json:
  - changed-files:
      - any-glob-to-any-file: "**/*.json"

documentation:
  - changed-files:
      - any-glob-to-any-file:
          - "docs/**/*"
          - "README.md"

ci:
  - changed-files:
      - any-glob-to-any-file: ".github/**/*"

tests:
  - changed-files:
      - any-glob-to-any-file: "tests/**/*"
