default_install_hook_types = ["pre-commit", "commit-msg"]

[[repos]]
repo = "builtin"
hooks = [
  { id = "trailing-whitespace", exclude = "backlog/" },
  { id = "end-of-file-fixer", exclude = "backlog/" },
  { id = "check-yaml" },
  { id = "check-json" },
  { id = "check-toml" },
  { id = "check-added-large-files" },
  { id = "check-merge-conflict" },
  { id = "detect-private-key" },
  { id = "mixed-line-ending", args = ["--fix=lf"] },
]

[[repos]]
repo = "https://github.com/astral-sh/ruff-pre-commit"
rev = "v0.11.2"
hooks = [
  { id = "ruff", args = ["--fix", "--exit-non-zero-on-fix"],
    exclude = "backlog/|scripts/" },
  { id = "ruff-format", exclude = "backlog/|scripts/" },
]

[[repos]]
repo = "https://github.com/pre-commit/mirrors-mypy"
rev = "v1.15.0"
hooks = [
  { id = "mypy", additional_dependencies = ["types-python-dateutil"],
    args = ["--ignore-missing-imports"],
    files = "^custom_components/rig_for_red/" },
]

[[repos]]
repo = "local"

[[repos.hooks]]
id = "cog-verify"
name = "conventional commit"
language = "system"
entry = "bash -c 'if ! head -1 \"$1\" | grep -qE \"^Merge \"; then exec cog verify --file \"$1\"; fi' --"
stages = ["commit-msg"]
