name: Conventional Commits
on:
  pull_request:
  push:
    branches: [main, dev]
permissions:
  contents: read
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 0
      - name: Conventional commit check
        shell: bash
        run: |
          curl -sL "https://github.com/cocogitto/cocogitto/releases/download/v7.0.0/cocogitto-7.0.0-x86_64-unknown-linux-musl.tar.gz" | tar xz -C /usr/local/bin cog
          chmod +x /usr/local/bin/cog
          cog check --from-latest-tag
