name: prek
on:
  pull_request:
  push:
    branches: [main, dev]
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
jobs:
  prek:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
      - uses: j178/prek-action@01345c78b7de7d79edf368729212760396ba9345 # v2
