name: prek
on:
  pull_request:
  push:
    branches: [main, dev]
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
jobs:
  prek:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: j178/prek-action@01345c78b7de7d79edf368729212760396ba9345 # v2
