name: Release Please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@7987652be64e4aa0c9bf1e0a4757c6f9503db655 # v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
